### ISSUE TITLE
issue with get_bars lookback 

### ISSUE THREAD

**Issue by rastegar527** [ranaroussi/qtpylib#46] opened 2016-12-18 23:12 UTC
Hi Ran,

While connecting to IB demo account I came across a problem with bars: 

I have four instruments `['IBKR', 'AAPL', 'OXY', 'SLB']`. I run the blotter and strategy and I fetch the bars for each of these instruments with loopback 28.  I let the scripts run for more than 30mins. My expectation was that I will be able to receive bars for loopback = 28 (so the length of bars = 28) . However, it is not the case.

here is the some of the output after 30 min :

AAPL 5
IBKR 6
SLB 6
OXY 6
AAPL 6
IBKR 7
SLB 7
OXY 6
AAPL 7

Here is the code:

```python
from qtpylib.algo import Algo
from qtpylib.indicators import macd#, air
import pandas as pd
from datetime import date time
import datetime

class TestStrategy(Algo):
    def on_start(self):
         pass

    def on_tick(self, instrument):
        pass

    def on_bar(self, instrument):      
        lookback = 28
        for symbol in self.instruments:
            instr = self.get_instrument(symbol)
            bars = instr.get_bars(lookback = loopback)
            print(symbol, len(bars))
        
if __name__ == "__main__":
    strategy = TestStrategy(
        #instruments = prescreening('2014-04-25', '2014-04-29'),
        instruments = ['IBKR', 'AAPL', 'OXY', 'SLB'], 
        resolution  = "1T" # 1Min bar resolution (Pandas "resample" resolutions)
    )
    strategy.run()
```

**Comment by ranaroussi** [comment] 2016-12-19 06:31
I'm looking into this, but you have some errors in your code...

```python
from datetime import date time # <== did you mean: datetime ?

...

def on_bar(self, instrument):      
    lookback = 28
    for symbol in self.instruments:
        instr = self.get_instrument(symbol)
        bars = instr.get_bars(lookback = loopback) # <== did you mean: lookback ?
        print(symbol, len(bars))
```

Also, you can achieve the same `lookback` functionality automatically by using `bar_window=28` in your strategy initializer.

**Comment by rastegar527** [comment] 2016-12-19 13:31
Datetime was in the code. This typo was introduced after editing the code for here : ). I'll also double check with bar_windows to see if I get the same issue. Thanks for looking into it Ran!

**Comment by ranaroussi** [comment] 2016-12-19 17:59
Please upgrade to the latest version...

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

... and let me know if there's an improvement :)

**Comment by rastegar527** [comment] 2016-12-20 00:23
I run it and there is now a problem with sampling rate. I receive couple of sample per each minute:

--------------------
2016-12-19 18:17:05.235610
IBKR 6
AAPL 6
SLB 6
OXY 6
--------------------
2016-12-19 18:18:00.960181
IBKR 6
AAPL 7
SLB 6
OXY 6
--------------------
2016-12-19 18:18:02.350345
IBKR 6
AAPL 7
SLB 7
OXY 6
--------------------
2016-12-19 18:18:02.812691
IBKR 6
AAPL 7
SLB 7
OXY 7
--------------------
2016-12-19 18:18:03.949643
IBKR 6
AAPL 7
SLB 7
OXY 7
--------------------

**Comment by ranaroussi** [comment] 2016-12-20 09:29
That's actually a feature, not a bug... 

You should get an `on_bar()` event for each new bar for each symbol. You didn't so far due to a bug that QTPyLib had.

I've improved the code in version 1.5.5. I recommend you upgrade and retest :)

**Comment by rastegar527** [comment] 2016-12-20 11:52
Thanks, Ran. Will do.

**Comment by rastegar527** [comment] 2016-12-21 02:09
Ok. Now I get a bar per each symbol. Two questions:

1) Is on_bar nonblocking? Let's say at minute X, I receive a bar for OXY, while on_bar is called for that event, a new bar arrives for XOM. What happens? Would a new on_bar be called immidiately or will the system wait for the last on_bar finishes before calling a new one? This is important to me since for my strategy I'm looking at all S&P500 stocks. with the current implementation, I receive 500 events each minute which (a) can potentially cause race condition if on_bar is nonblocking and (b) can cause blockage of on_bar is blocking. I don't know if you feel the same way, but with many symbols, receiving all the bars together at each minute make more sense. 

2) Is there any place in the code that I need to change DU account number to be able to connect to my paper trading account instead of demo account DU15104? Would you mind if I give you my paper trading account so you could test it on your machine and see if you see the same issue as I see in #47? I have exhausted all my options with IB.

**Comment by ranaroussi** [comment] 2016-12-21 18:18
Version `1.5.52` was just released with all market data events made asynchronous / non-blocking :)

You can see the non blocking in action with this sample strategy:

```python
from qtpylib.algo import Algo
from pandas import to_datetime
from time import sleep

class TestStrategy(Algo):
    def on_bar(self, instrument):
        bars = instrument.bars
        dt = to_datetime(str(bars.index.values[-1])).strftime("%H:%M:%S")

        print("---", instrument, dt, "---")
        sleep(3)
        print("===> DELEYAED", instrument, dt)
```

**Comment by ranaroussi** [comment] 2016-12-22 15:08
Closing issue

**Closed by ranaroussi** 2016-12-22 15:08 UTC
