### ISSUE TITLE
Exception in message dispatch

### ISSUE THREAD

**Issue by rastegarr** [ranaroussi/qtpylib#32] opened 2016-11-27 22:45 UTC
I run the example/blotter.py successfully and then I run a simple strategy that only prints ticks received for IBKR stock. However I get the following "exception in message dispatch". Can you please let me know if this is a bug or I have some other issues. TWS is connected and mysql is running. Thanks!

```
$ python print_data.py 
Server Version: 76
TWS Time at connection:20161127 16:40:06 CST
27-Nov-16 16:40:07 ERROR     Exception in message dispatch.  Handler 'handleServerEvents' for 'contractDetailsEnd'
Traceback (most recent call last):
  File "/Users/reza/anaconda3/envs/qtpylib_trading/lib/python3.5/site-packages/ib/opt/dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "/Users/reza/anaconda3/envs/qtpylib_trading/lib/python3.5/site-packages/ezibpy/ezibpy.py", line 295, in handleServerEvents
    self.handleContractDetails(msg, end=True)
  File "/Users/reza/anaconda3/envs/qtpylib_trading/lib/python3.5/site-packages/ezibpy/ezibpy.py", line 411, in handleContractDetails
    self.portfolio[newString] = self.portfolio[oldString]
KeyError: 'IBKR'
Tick: {'symbol': 'IBKR', 'last': 38.88, 'lastsize': 1, 'bidsize': 1, 'symbol_group': 'IBKR', 'datetime': Timestamp('2016-11-27 16:39:32'), 'asset_class': 'STK', 'asksize': 1, 'bid': 38.87, 'ask': 38.91, 'opt_price': nan}
```

**Comment by ranaroussi** [comment] 2016-11-28 07:47
Sorry about that... This was caused by a recent update to the [ezIBpy](https://github.com/ranaroussi/ezibpy) library, which QTPyLib is using to communicate with Interactive Brokers.

I've fixed the bug in [ezIBpy](https://github.com/ranaroussi/ezibpy) and you should see this error gone after you upgrade to its latest version (1.12.40):

```
$ pip install ezibpy --upgrade --no-cache-dir
```

LMK if this solves the problem,

Ran

**Comment by ranaroussi** [comment] 2016-11-29 19:56
Closing this issue. Please reopen if not solved

**Closed by ranaroussi** 2016-11-29 19:56 UTC

**Comment by rastegar527** [comment] 2016-11-30 16:26
It is fixed now. Thanks!

**Comment by rastegar527** [comment] 2016-12-17 06:14
Hi Ran, I started getting the same issue I reported here before. It was fixed but after new updates it started showing up.
