### ISSUE TITLE
Orders don't work

### ISSUE THREAD

**Issue by jkleint** [ranaroussi/qtpylib#28] opened 2016-11-15 02:57 UTC
I can't seem to get any orders to go through at all; no errors, but no orders.  Stocks, forex, and futures.  For example:

```
from time import time
import sys
import logging

from qtpylib.algo import Algo

logging.getLogger('ezibpy').setLevel(logging.DEBUG)


class SecBar(Algo):
    def on_fill(self, instrument, order):
        print('fill', order)

    def on_bar(self, instrument):
        bar = instrument.bar
        print('bar {:.0f} {}'.format(time(), instrument.bar['datetime']), ' '.join('{:.4f}'.format(bar[val]) for val in ('open', 'high', 'low', 'close', 'volume')), file=sys.stderr)
        instrument.order("BUY", 1)


if __name__ == '__main__':
    SecBar(["AAPL"], '1S', force_resolution=True).run()
```

Just prints bars all day.

If I run the [ezibpy example](https://github.com/ranaroussi/ezibpy#submit-an-order) it works fine.  No idea what's going on, because there isn't really any coherent logging, so maybe I'll start there.

**Comment by ranaroussi** [comment] 2016-11-15 05:52
I'm not sure what the problem is. Just ran your code above and it worked without problem...

```
$ python strategy.py

Server Version: 76
TWS Time at connection:20161115 07:49:24 IST

bar 1479188968 2016-11-15 05:49:28 111.0500 111.0500 111.0500 111.0500 2.0000
fill {'symbol': 'AAPL', 'time': datetime.datetime(2016, 11, 15, 7, 49, 27), 'status': 'FILLED', 'id': 2, 'parentId': 0, 'reason': None, 'avgFillPrice': 111.05}
bar 1479188969 2016-11-15 05:49:29 111.0400 111.0400 111.0400 111.0400 1.0000
fill {'symbol': 'AAPL', 'time': datetime.datetime(2016, 11, 15, 7, 49, 27), 'status': 'FILLED', 'id': 3, 'parentId': 0, 'reason': None, 'avgFillPrice': 111.05}
bar 1479188970 2016-11-15 05:49:30 111.0400 111.0400 111.0400 111.0400 1.0000
fill {'symbol': 'AAPL', 'time': datetime.datetime(2016, 11, 15, 7, 49, 28), 'status': 'FILLED', 'id': 4, 'parentId': 0, 'reason': None, 'avgFillPrice': 111.05}
...
```

I know it probably is - but Is your TWS/GW configured  with **Bypass Order Precautions for API Orders**?

**Comment by jkleint** [comment] 2016-11-15 21:06
> Is your TWS/GW configured with Bypass Order Precautions for API Orders?

Yes.  I'm using the demo account if that makes any difference.

I think it's that the connection to TWS hasn't actually been made when the first bars/orders happen, and then subsequent orders don't get entered because there is a dead order pending.  I'm working on properly updating connection state and then waiting for it before starting.

**Comment by jkleint** [comment] 2016-11-16 03:27
Turns out I was never even connected to TWS, because the command-line arg defaults were overriding the ibport/ibclient I was passing to Algo(), and there was no/poor logging or error handling around this so I never knew it.  I spent several days fighting with this.  

The design of silently integrating command-line arguments is hugely misleading (["explicit is better than implicit"](https://www.python.org/dev/peps/pep-0020/), etc.), has already caused bugs/frustration, and will continue to do so in the future.  I have kept it (and fixed its bugs), but I strongly recommend making it explicit (and non-default).  Plenty of people will want to make Algos buried deep in some other system having nothing to do with the command line, and this design will bite them.

Another (unresolved) issue is that when you place an order and it has an error, it stays in the pending queue and prevents other orders from going through.  I added a warning log when this happens, but it will need attention.

Patch in #29.

**Comment by ranaroussi** [comment] 2016-11-16 20:31
As always, great job! I've merged your code and added some changes of my own. 

As for the pending order issue, pending orders can be cleared by setting `self.orders.pending = {}`, tho I wasn't able to replicate the issue, so I'm not sure where I should implement the fix.

**Closed** 2016-11-16 20:31 UTC
